include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - unnecessary_this
    - directives_ordering

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    unused_import: warning
    dead_code: warning
